SELECT GENERATE_SERIES(0, 100, 5)

SELECT GENERATE_SERIES(100, 0, -5)

SELECT X, X * 10 FROM 
GENERATE_SERIES(100, 0, -5) AS F(X)

SELECT X FROM
GENERATE_SERIES('2001-10-01'::TIMESTAMP, '2002-10-01'::TIMESTAMP, '1 day') as F(X)

SELECT RANDOM() * 1000

SELECT TRUNC(RANDOM() * 1000 + 1)
FROM GENERATE_SERIES(1, 1000)

SELECT TRUNC(RANDOM() * (100-50) + 50)

SELECT * FROM PAYMENT
WHERE PAYMENT_ID IN(
SELECT TRUNC(RANDOM() * (32098-17503) + 17503)
FROM GENERATE_SERIES(1,100))

-- CREATING AN FUNCTION --

CREATE OR REPLACE FUNCTION RANDOM_PAYMENTS(COUNTER INT) RETURNS SETOF PAYMENT
AS $$
DECLARE
	START_ID INT;
	END_ID INT;
BEGIN
	SELECT MIN(PAYMENT_ID) FROM PAYMENT INTO START_ID;
	
	SELECT MAX(PAYMENT_ID) FROM PAYMENT INTO END_ID;
	
	RETURN QUERY 
		(SELECT * FROM PAYMENT
			WHERE PAYMENT_ID IN(
			SELECT TRUNC(RANDOM() * (END_ID - START_ID) + START_ID)
			FROM GENERATE_SERIES(1,COUNTER)));
END	
$$ LANGUAGE PLPGSQL

SELECT * FROM RANDOM_PAYMENTS(4)








