CREATE TABLE USERS(
	ID INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(255)
)

ALTER TABLE USERS ADD CONSTRAINT ID UNIQUE(ID)

CREATE TABLE POSTS(
	ID SERIAL PRIMARY KEY NOT NULL,
	BODY TEXT NOT NULL,
	SCORE INT DEFAULT 0,
	AUTHOR_ID INT NOT NULL,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	SEARCH_FIELD TSVECTOR
);

CREATE INDEX IDX_POST_SEARCH ON POSTS USING GIN(SEARCH_FIELD);

CREATE TABLE QUESTIONS(
	QUESTION_ID INT PRIMARY KEY NOT NULL,
	TITLE VARCHAR(255),
	VIEW_COUNT INT NOT NULL DEFAULT 0,
	ANSWER_ID INT,
	TAGS VARCHAR(255)
) INHERITS (POSTS);

CREATE TABLE ANSWERS(
	ANSWER_ID INT PRIMARY KEY NOT NULL,
	QUESTION_ID INT NOT NULL
) INHERITS (POSTS);

CREATE TABLE COMMNETS(
	COMMENT_ID SERIAL NOT NULL PRIMARY KEY,
	POST_ID INT NOT NULL
) INHERITS (POSTS);














