CREATE OR REPLACE VIEW RAW_SALES AS
SELECT TITLE
	, DESCRIPTION
	, LENGTH
	, RATING
	, PY.AMOUNT
	, PAYMENT_DATE
	, DATE_PART('QUARTER', PAYMENT_DATE) AS QUARTER
	, DATE_PART('MONTH', PAYMENT_DATE) AS MONTH
	, DATE_PART('YEAR', PAYMENT_DATE) AS YEAR
	, CONCAT('Q',DATE_PART('QUARTER', PAYMENT_DATE) :: TEXT, '-',DATE_PART('YEAR', PAYMENT_DATE) :: TEXT) AS QYEAR
	, CASH_WORDS(AMOUNT :: MONEY) AS SPELLING_IT_OUT
	, TO_TSVECTOR(CONCAT(TITLE, DESCRIPTION)) AS SEARCH_FIELDS
	FROM FILM AS FI
	
	INNER JOIN INVENTORY INV
	ON INV.FILM_ID = FI.FILM_ID

	INNER JOIN RENTAL RT
	ON RT.INVENTORY_ID = INV.INVENTORY_ID

	INNER JOIN PAYMENT PY
	ON PY.RENTAL_ID = RT.RENTAL_ID


	SELECT * FROM RAW_SALES